version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - ./app:/home
      - /home/node_modules
    working_dir: /home
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - greenn-nodejs-network
    depends_on:
      - mysql
      - redis

  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3301:3306"
    restart: always
    networks:
      - greenn-nodejs-network
    volumes:
      - ./database:/database_source
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: redis:latest
    restart: always
    networks:
      - greenn-nodejs-network

networks:
  greenn-nodejs-network:
    driver: bridge

volumes:
  mysqldata:
