import { ProductsRepositoryInterface } from 'src/domain/products/products.repository.interface';

export class ProductsRepository implements ProductsRepositoryInterface {
  async findBySellerId(sellerId: number) {
    return {
      name: 'product-test',
    };
  }

  async create() {
    return {
      name: 'product-test',
    };
  }

  async findOne(id: number) {
    return {
      data: {
        id: 673,
        name: 'Venda ',
        description:
          'Aten\u00e7\u00e3o, n\u00e3o alterar informa\u00e7\u00f5es desse produto\nAten\u00e7\u00e3o, n\u00e3o alterar informa\u00e7\u00f5es desse produto\nAten\u00e7\u00e3o, n\u00e3o alterar informa\u00e7\u00f5es desse produto\nAten\u00e7\u00e3o, n\u00e3o alterar informa\u00e7\u00f5es desse produto\nAten\u00e7\u00e3o, n\u00e3o alterar informa\u00e7\u00f5es desse produto',
        category_id: 2,
        stock: -13,
        type: 'TRANSACTION',
        amount: 15,
        period: null,
        thank_you_page: 'https://greenn.com.br',
        affiliation: 0,
        comission: 14,
        created_at: '2023-01-20T12:37:49.000000Z',
        updated_at: '2023-07-10T12:52:06.000000Z',
        seller_id: 278,
        slug: 'venda',
        method: 'CREDIT_CARD,TWO_CREDIT_CARDS,BOLETO,PIX,PAYPAL',
        warranty: 10,
        url_callback: null,
        trial: null,
        is_checkout_address: 0,
        bump_description: null,
        social_prove_id: null,
        proposal_minimum: 0,
        banner_checkout: null,
        allow_proposal: 0,
        affiliation_approbation: 0,
        affiliation_public: 0,
        pending_motive: null,
        is_active: 1,
        deleted_at: null,
        affiliation_proposal: 0,
        max_boleto_installments: 0,
        status: 'APPROVED',
        max_subscription_installments: null,
        max_installments: 12,
        max_comission: 100,
        category_fiscal: 'SERVICE',
        fiscal_code: null,
        allowed_coupon: 1,
        format: 'INFOPRODUCT',
        instructions: null,
        smart_sale: 1,
        fixed_installments: null,
        smart_sale_installments: null,
        has_stock: 0,
        can_be_gifted: 1,
        has_shipping_fee: 0,
        has_custom_shipping_address: 0,
        height: 0,
        width: 0,
        length: 0,
        weight: 0,
        address_product_id: null,
        co_seller_display_id: null,
        is_public_allowed: false,
        charges: null,
        no_interest_installments: 0,
        seller_fee: 4.98,
        affiliate_fee: 4.99,
        warranty_checkout: 1,
        smart_sale_dynamic_installments: 1,
        pre_selected_installment: null,
        is_heaven: 0,
        type_shipping_fee: 'DYNAMIC',
        amount_fixed_shipping_fee: 15,
        shipping_fee_is_recurring: 1,
        affiliation_lead: 0,
        high_ticket_fee: null,
        mentoring_period: null,
        mentoring_duration: null,
        start_date: null,
        end_date: null,
        start_time: null,
        end_time: null,
        location: null,
        product_type_id: null,
        status_changed_at: null,
        enable_invoice_items: false,
        items_for_invoice: null,
        has_cashback: 0,
        is_ia_approval: null,
        recommendation: null,
        negative_reasons: null,
        positive_reasons: null,
        are_non_transferable: 0,
        in_stock: true,
        status_product: 'APPROVED',
        images: [
          {
            id: 141900,
            product_id: 673,
            path: 'https://greenn.nyc3.digitaloceanspaces.com/products/e5MsoOpFxb.jpg',
            created_at: '2023-08-23T16:51:43.000000Z',
            updated_at: '2023-08-23T16:51:43.000000Z',
          },
        ],
        seller: {
          id: 278,
          name: 'Dev Greenn Test',
          cellphone: '+5544998741312',
          is_heaven: 1,
          is_greenn: 1,
          company_id: 1747,
          internacional_company_id: 4517,
          company: {
            id: 1747,
            name: 'Teste DEV',
            fantasy_name: 'Teste DEV FANTASIA',
            telephone: '+55119795476862',
            email: 'dev@email.com.br',
            support_telephone: '+5511979547686',
          },
        },
        pixels: [
          {
            id: 97,
            pixel_id: '123456',
            type: 'FACEBOOK',
            product_id: 673,
            created_at: '2021-09-22T04:02:09.000000Z',
            updated_at: '2022-12-28T18:19:27.000000Z',
            view: 1,
            conversion: 1,
            web: 1,
            token: '',
            api: 0,
            optimization: 0,
            domain_id: null,
            confirmed_only: 0,
            user_id: 257,
            label: null,
            amount: 0,
            host: 'apipixel.greenn.com.br',
          },
          {
            id: 101,
            pixel_id: '111',
            type: 'FACEBOOK',
            product_id: 673,
            created_at: '2021-09-22T05:00:20.000000Z',
            updated_at: '2021-09-22T05:00:20.000000Z',
            view: 1,
            conversion: 1,
            web: 1,
            token: '',
            api: 0,
            optimization: 0,
            domain_id: null,
            confirmed_only: 0,
            user_id: 257,
            label: null,
            amount: 0,
            host: 'apipixel.greenn.com.br',
          },
          {
            id: 102,
            pixel_id: '11',
            type: 'FACEBOOK',
            product_id: 673,
            created_at: '2021-09-22T05:20:33.000000Z',
            updated_at: '2021-09-22T05:20:33.000000Z',
            view: 1,
            conversion: 1,
            web: 1,
            token: '',
            api: 0,
            optimization: 0,
            domain_id: null,
            confirmed_only: 0,
            user_id: 257,
            label: null,
            amount: 0,
            host: 'apipixel.greenn.com.br',
          },
          {
            id: 104,
            pixel_id: '33',
            type: 'FACEBOOK',
            product_id: 673,
            created_at: '2021-09-22T05:24:22.000000Z',
            updated_at: '2021-09-22T05:24:22.000000Z',
            view: 1,
            conversion: 1,
            web: 1,
            token: '',
            api: 0,
            optimization: 0,
            domain_id: null,
            confirmed_only: 0,
            user_id: 257,
            label: null,
            amount: 0,
            host: 'apipixel.greenn.com.br',
          },
          {
            id: 12239,
            pixel_id: '2343434345',
            type: 'FACEBOOK',
            product_id: 673,
            created_at: '2023-08-22T13:48:53.000000Z',
            updated_at: '2023-08-22T13:48:53.000000Z',
            view: 1,
            conversion: 1,
            web: 1,
            token: '',
            api: 0,
            optimization: 0,
            domain_id: 1976,
            confirmed_only: 0,
            user_id: 278,
            label: null,
            amount: 0,
            host: 'apipixel.greenn.com.br',
          },
        ],
        category: {
          id: 2,
          name: 'Apps & Software',
          created_at: '2020-08-12T14:51:55.000000Z',
          updated_at: '2020-08-12T14:51:55.000000Z',
        },
        product_id: 673,
        hash: '5cZ2Qs',
        default: 1,
        reason: null,
        analised: 0,
        currency_id: 1,
        allow_offer_link: 0,
        offer_redirect_id: null,
        offer_group_id: null,
        batch_order: null,
        status_offer: 'APPROVED',
        custom_charges: [],
        offer_redirect: null,
        is_dlocal: false,
      },
      type: 'COMMON',
      custom_checkout: {
        theme: 'light',
        theme_color: '#00e4a0',
        top_thumb: null,
        bottom_thumb: null,
        side_thumb: null,
        side_thumb_mobile: null,
        logotipo: null,
        theme_color_bg: 'rgba(0, 228, 160, 0.3)',
        button_text: null,
        trial_position: null,
        trial_info: null,
        jivochat_id: null,
        step_checkout: 'default',
        purchase_notification: 'off',
        maximum_purchase_notification_interval: null,
        minimum_purchase_notification_interval: null,
        scarcity: 'off',
        scarcity_title: null,
        scarcity_subtitle: null,
        scarcity_time: null,
        scarcity_background_color: null,
        how_get_purchase_notification: null,
        quantity_purchase_notification: null,
        type_purchase_notification: null,
        ob_custom: null,
        ob_title: null,
        ob_subtitle: null,
        ob_description: null,
        ob_border: null,
        ob_border_px: null,
        ob_background_color: null,
        warranty_checkout: null,
        whatsapp_number: null,
        whatsapp_msg: null,
        zopim_id: null,
        whatsapp_button: null,
        confirmation_email: null,
        exit_pop_up: null,
        image_exit_pop_up: null,
        title_exit_pop_up: null,
        button_exit_pop_up: null,
        link_exit_pop_up: null,
        text_button_exit_pop_up: null,
        description_exit_pop_up: null,
      },
      purchase_notification: [],
      checkout_payment: {
        data: {
          symbol_currency: 'R$',
          rate: 1,
          from: 'BRL',
          to: 'BRL',
          base_amount: 15,
          amount: 15,
        },
        token: 'default',
        conversion: false,
        price: 15,
        base_currency: 'BRL',
        seller_id: 278,
        paypal: {
          amount: 15,
          currency: 'BRL',
          symbol_currency: 'R$',
        },
      },
      allow_free_offers: null,
    };
  }
}
